site_name: Alphavantage Java
repo_name: crazzyghost/alphavantage-java
repo_url: https://github.com/crazzyghost/alphavantage-java
nav:
    - Overview: index.md
    - Recipes: 
      - Stock Time Series: timeseries.md
      - Forex (FX): forex.md
      - CryptoCurrencies: crypto.md
      - Exchange Rates: exchangerate.md
      - Technical Indicators: indicators.md
    - Changelog: changelog.md
theme:
  name: material
  features:
    - instant
  font:
    text: "Roboto"
    code: Roboto Mono
  palette:
    primary: deep orange
    accent: deep orange
extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tabbed

